### PR TITLE
Add additional RSS feeds

### PR DESCRIPTION
**Pull request by jwoglom**
Pretty straightforward -- I haven't tested the RSS tidbyt app's ability to fetch these, but I looked at each URL and sanity checked the description/item elements.

### CODE REVIEW

**Comment by jvivona** [comment]
The CNN feeds are dead.  I removed the CNN app of the Tidbyt community apps repo a couple of weeks ago, because WBD has decided to retire those.  if you look the last article in that feed is from April 2023.  see the discussion here:  https://discuss.tidbyt.com/t/cnn-app-not-updating/6599/3

Let me look at NY Times, I may split it into it's own app if it's got sections we can use - would rather there be purpose built apps instead of jamming a lot of section feeds from 1 source into the generic app. 

I'll take a look in the morning when I get into the office, but I'll get it done this week - no matter what at a minimum, I'll get the ARS Technica in there..   Do you know if they have sections as well?   break it out into it's own app if so?

**Comment by jwoglom** [comment]
Ah, good callout with the CNN feed... unfortunate that they're not updating it anymore. 

Up to you if you think splitting out the other news sites into separate apps is worth it, I just liked the design of how your app scrolls news feeds :)

**Comment by jvivona** [comment]
I'm merging ARS Technica into the JSON list, but NY Times, I've submitted a separate app for with options for 17 sections from the site.    Thanks so much for pointing both of these out & getting the URLs - you are making my life easier.

**Comment by jvivona** [comment]
@jwoglom - just FYI - got an note from Tidbyt - they aren't going to be able to merge the NY Times app - apparently the NYT reached out of them a while ago & told them to pull any feeds from their apps/devices as a Terms of Service violation.   So tidbyt doesn't want to go up against NYT again.

**Pull request closed without merging**
